### PR TITLE
Windows build fix

### PR DESCRIPTION
**Pull request by janoc**
Boost is autolinked in Windows using #pragmas by default , this avoids duplicate symbol definition errors.

### CODE REVIEW

**Comment by nekipelov** [comment]
Thank you. But I can forget and commit or accept pull request without `IF(NOT MSVC)` for the boost libraries. It is better to add  `-DBOOST_ALL_NO_LIB` to disable auto-linking?

**Comment by janoc** [comment]
OK, I have tried to disable autolinking, but that is a bit complicated in Windows. I had to change the code for the benchmark example to use the imported targets otherwise it wouldn't link with Boost 1.60 on my machine. I have also added the missing date_time library.

**Comment by janoc** [comment]
Hopefully fixed - had to revert it to the old style ${Boost_LIBRARIES} variable instead of the import targets because that doesn't work well/at all with the ancient version of CMake in Travis.

**Comment by nekipelov** [comment]
We have two problems:

1. I want to keep using libboost1.48-dev on travis-ci to check compatibility with old boost version.
2. We need to keep the way for static linking with boost with `-DBoost_USE_STATIC_LIBS="ON"`.

Can you try to use my fix from branch fix-boost-linking?

**Comment by janoc** [comment]
That is building for me. I have updated Travis to use Trusty (and thus newer Boost), because of the CMake problems with the imported targets. However, that has been reverted, because it doesn't work even on Trusty (the CMake is too ancient).

BTW, you can (and perhaps should) use ${Boost_LIBRARIES} instead of the individual 
${Boost_SYSTEM_LIBRARY} ${Boost_DATE_TIME_LIBRARY} ${Boost_UNIT_TEST_FRAMEWORK_LIBRARY} 

In that way you will not forget to add the correct libraries to the linker - they get added to Boost_LIBRARIES automatically depending on which components you choose in FindPackage(Boost ...). Having extras there that are not needed is harmless, the linker will ignore them.

**Pull request closed without merging**
