### PR TITLE
result name clash

### PR DESCRIPTION
**Pull request by burner**
result is also a function

### CODE REVIEW

**Comment by burner** [comment]
I'm not sure why travis fails maybe because gcc 4.6 is to old

**Comment by burner** [comment]
the error "redisparser.cpp:364:47: error: ‘ParseParse’ was not declared in this scope" is strange.

The work ParseParse does not appear once in the source file

p.s. the test pass with current gcc and current clang

**Comment by nekipelov** [comment]
-std::pair<size_t, ParseResult> result
    +std::pair<size_t, ParseParse> resultParse

**ParseResult** vs **ParseParse**. 

Please rename "resultParse" to "parseResult"

**Comment by burner** [comment]
fixed

**Comment by nekipelov** [comment]
thank you

**Comment by burner** [comment]
thank you

**Pull request merged**
